export const serverErrors = {
	sighIn: {
		PHONE_NUMBER_UNOCCUPIED: 'PHONE_NUMBER_UNOCCUPIED',
		PHONE_CODE_INVALID: 'PHONE_CODE_INVALID',
		PHONE_CODE_EXPIRED: 'PHONE_CODE_EXPIRED',
		SESSION_PASSWORD_NEEDED: 'SESSION_PASSWORD_NEEDED'
	}
};
