name: CI

on: 
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    env:
      HEROKU_APP: contest-telegram-client
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}

    steps:
    - name: Deploying to Heroku
      uses: actions/heroku@1.0.0
