name: CI

on: 
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Deploying to Heroku
        env:
          HEROKU_APP: contest-telegram-client
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          docker build -t web ../Dockerfile
          heroku container:push web -a $HEROKU_APP
          heroku container:release web -a $HEROKU_APP
